# Generated by Django 3.0.5 on 2021-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
