# Generated by Django 3.0.5 on 2021-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210628_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN'), ('moderator', 'MODERATOR')], default='user', max_length=40),
        ),
    ]
