# Generated by Django 3.0.5 on 2021-06-15 15:08

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210615_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(blank=True, validators=[api.validators.year_validator], verbose_name='Год выпуска произведения'),
        ),
    ]
