# Generated by Django 3.0.5 on 2021-06-22 14:28

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210622_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, validators=[api.validators.year_validator], verbose_name='Год выпуска произведения'),
        ),
    ]
