# Generated by Django 3.0.5 on 2021-06-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210615_0756'),
        ('api', '0005_auto_20210615_1545'),
    ]

    operations = [
    ]
